spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: msvc-product
          uri: http://localhost:9003
          predicates:
            - Path=/api/product/**
          filters:
            - AuthenticationFilter

        - id: msvc-supplier
          uri: http://localhost:9005
          predicates:
            - Path=/api/supplier/**
          filters:
            - AuthenticationFilter


server:
  port: 8082