spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: servicel
          uri: http://localhost:9001
          predicates:
            - Path=/api/saludo/**
          filters:
            - AuthenticationFilter
        - id: service2
          uri: http://localhost:9002
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthenticationFilter

server:
  port: 8082